import React from 'react';
import useSEO from '../../hooks/useSEO';
import './Legal.css';

const Terms = () => {
  useSEO({
    title: 'Terms and Conditions',
    description: 'Terms and conditions for using kitsunechaos Lab tools and experiments.'
  });

  return (
    <div className="legal-page page-enter">
      <div className="container">
        <article className="legal-content">
          <h1>Terms and <span className="gradient-text">Conditions</span></h1>
          <span className="legal-last-updated">Last Updated: March 22, 2026</span>

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>By accessing or using the tools and experiments provided by kitsunechaos Lab ("we", "us", or "our"), including but not limited to Grant Proposal AI, you agree to be bound by these Terms and Conditions.</p>
          </section>

          <section>
            <h2>2. Use of Services</h2>
            <p>Our tools are provided for personal and professional use. You agree not to:</p>
            <ul>
              <li>Use the services for any illegal purpose.</li>
              <li>Attempt to reverse engineer or disrupt the services.</li>
              <li>Share account access in violation of plan limits.</li>
            </ul>
          </section>

          <section>
            <h2>3. AI Content Clause</h2>
            <p>Tools like Grant Proposal AI use artificial intelligence to generate content. While we strive for accuracy, we do not guarantee the completeness or correctness of AI-generated drafts. You are responsible for reviewing and verifying all generated content before use.</p>
          </section>

          <section>
            <h2>4. Intellectual Property</h2>
            <p>All software, designs, and systems remains the exclusive property of kitsunechaos Lab. Content generated by you through our tools belongs to you, subject to your compliance with these terms.</p>
          </section>

          <section>
            <h2>5. Disclaimer of Warranties</h2>
            <p>The services are provided "as is" without any warranties of any kind. We disclaim all warranties, whether express or implied, including merchantability and fitness for a particular purpose.</p>
          </section>

          <section>
            <h2>6. Limitation of Liability</h2>
            <p>In no event shall kitsunechaos Lab be liable for any indirect, incidental, special, or consequential damages arising out of your use of the services.</p>
          </section>

          <section>
            <h2>7. Contact Information</h2>
            <p>For questions about these Terms, please contact us at support@kitsunechaos.com.</p>
          </section>
        </article>
      </div>
    </div>
  );
};

export default Terms;
